<?php

declare(strict_types=1);

namespace Affise\Sdk\User;

/**
 * Class Role
 */
abstract class Role
{
    public const ROLE_ADMIN = 'ROLE_ADMIN';
    public const ROLE_MANAGER_AFFILIATE = 'ROLE_MANAGER_AFFILIATE';
    public const ROLE_MANAGER_SALES = 'ROLE_MANAGER_SALES';
    public const ROLE_SECTION_OFFER = 'ROLE_SECTION_OFFER';
    public const ROLE_SECTION_SUPPLIER = 'ROLE_SECTION_SUPPLIER';
    public const ROLE_SECTION_DASHBOARD = 'ROLE_SECTION_DASHBOARD';
    public const ROLE_SECTION_NEWS = 'ROLE_SECTION_NEWS';
    public const ROLE_SECTION_CATEGORY = 'ROLE_SECTION_CATEGORY';
    public const ROLE_SECTION_PARTNER = 'ROLE_SECTION_PARTNER';
    public const ROLE_SECTION_PAYMENT = 'ROLE_SECTION_PAYMENT';
    public const ROLE_SECTION_TICKET = 'ROLE_SECTION_TICKET';
    public const ROLE_SECTION_STATS = 'ROLE_SECTION_STATS';
    public const ROLE_SECTION_STATS_COMMON = 'ROLE_SECTION_STATS_COMMON';
    public const ROLE_SECTION_STATS_CONVERSION = 'ROLE_SECTION_STATS_CONVERSION';
    public const ROLE_SECTION_STATS_SUPPLIER = 'ROLE_SECTION_STATS_SUPPLIER';
    public const ROLE_SECTION_STATS_OFFER = 'ROLE_SECTION_STATS_OFFER';
    public const ROLE_SECTION_STATS_COUNTRY = 'ROLE_SECTION_STATS_COUNTRY';
    public const ROLE_SECTION_STATS_CITY = 'ROLE_SECTION_STATS_CITY';
    public const ROLE_SECTION_STATS_OS = 'ROLE_SECTION_STATS_OS';
    public const ROLE_SECTION_STATS_GOAL = 'ROLE_SECTION_STATS_GOAL';
    public const ROLE_SECTION_STATS_DEVICE = 'ROLE_SECTION_STATS_DEVICE';
    public const ROLE_SECTION_STATS_LIMITS = 'ROLE_SECTION_STATS_LIMITS';
    public const ROLE_SECTION_STATS_PARTNER_POSTBACK = 'ROLE_SECTION_STATS_PARTNER_POSTBACK';
    public const ROLE_SECTION_STATS_SERVER_POSTBACK = 'ROLE_SECTION_STATS_SERVER_POSTBACK';
    public const ROLE_SECTION_AUTOMATION = 'ROLE_SECTION_AUTOMATION';
    public const ROLE_SECTION_STATS_COMPARISON = 'ROLE_SECTION_STATS_COMPARISON';
}
